### ISSUE TITLE
AutoVW Opening Pyxis

### ISSUE THREAD

**Issue by Brotocol** [Icydeath/ffxi-addons#1]
Seems like AutoVW only opens Pyxis maybe 60% of the time. It's not detecting it isn't opening them so it isn't retrying either. Any ideas? 

Also, thanks for updating this repository, it's been very useful.

**Comment by Icydeath** [comment]
Try using autowatch instead (in my repository)

**Comment by Brotocol** [comment]
Alright that seems to open them more reliably but when I set my other accounts to Leech mode or Slave, they spam inject open about 1000 times and crash playonline or break the ability to open the chest somehow.

**Comment by Icydeath** [comment]
This is the original creator (i think)
https://github.com/sethmccauley/Addons
looks like he updated it about 2 months ago. Idk if its newer or not than the one I have.... if you try his and it still isn't functioning correctly I'll try to make some time to fix it.

**Comment by Brotocol** [comment]
Hmm yeah tried his and it's still spamming, unfortunately. Thanks for checking it out.

**Comment by Icydeath** [comment]
added voidwatch.lua that I just found. idk if it works but you can test and see :)

**Comment by Brotocol** [comment]
I don't know if I'm just an idiot, but I can't seem to find the new one you uploaded haha.

**Comment by Icydeath** [comment]
nope was my fault forgot to use Push. Also i would continue using autowatch with your main, and use the 'voidwatch' with your alts to automate the pixie stuff. Good luck :P
