### ISSUE TITLE
Mouse Clicks Not Aligned (WarpMenu)

### ISSUE THREAD

**Issue by tizerheads** [Icydeath/ffxi-addons#10]
Hi,
I'm not sure if this can be edited in the lua or if it's a local settings issue, but i have to click the warp option below the one i want in the list for it to recognize the warp i actually want to use. I'm not sure if that makes actual sense, but as i'm typing this it does.

**Comment by Icydeath** [comment]
I haven't looked at this in a long time. I will take a look to see if it does the same thing for me.

**Comment by Icydeath** [comment]
@tizerheads 
I haven't had a chance to look into this yet, but I created a gui for superwarp that you may be interested in.
https://github.com/Icydeath/superwarp

If you follow the steps laid out in the readme it should be pretty easy to setup.
