### ISSUE TITLE
AutoCOR Fold and Snake Eye

### ISSUE THREAD

**Issue by garshane** [Icydeath/ffxi-addons#11]
If I have an 11 roll then it bust's but Bust status is evaded, it will still Fold and erase the 11 roll then restart the whole process.

If it uses Snake Eye and the recast timer procs to 0, then it will use Snake Eye again even though Snake Eye status is already up. 

Would some small delays help solve both of these to have time to check current statuses and prevent erasing 11 rolls and using Snake Eye when it's already active?

**Comment by Icydeath** [comment]
Increasing the delay may work, but I should investigate this further to see.

**Comment by Icydeath** [comment]
Fixed the fold issue and increased the delay just a bit to see if that resolves the Snake Eye issue. But I'll dig into the Snake Eye issue later today. Give it a try.
https://github.com/Icydeath/ffxi-addons/blob/master/AutoCOR/AutoCOR.lua

**Comment by Icydeath** [comment]
Actually, I see the issue. Will have it updated shortly.

**Comment by Icydeath** [comment]
Updated. Closing the issue. If any other issues please let me know. and sorry it took me a few weeks to get to this >.<;
