### ISSUE TITLE
AutoSkillChain Error

### ISSUE THREAD

**Issue by wjctampa** [Icydeath/ffxi-addons#12]
Hi Icy,

Since the last update Autoskillchain generates this error when trying to toggle on or switching skillchains.  

![AutoSkillchain Error](https://user-images.githubusercontent.com/6455221/115124982-5b8e6680-9f93-11eb-928e-40c572d4eb4e.png)

**Comment by Icydeath** [comment]
Interesting. I'm guessing this error occurred after using the cmd cycle_chain or the keybind to cycle chain?

I just tested it and used cycle_chain on 3 different characters (3 different jobs as well) and didn't encounter that error.

One thing you could try is to edit the file and replace line 57 with the following:
`selected_chain_index = chains and (selected_chain_index % #chains) + 1 or 1`
