### ISSUE TITLE
autowatch seems to relinquish Heavy metal pouch?

### ISSUE THREAD

**Issue by berkleyson** [Icydeath/ffxi-addons#13]
I ran Qilin using this over night 500~ times and 0 HMP drops in inventory. Every chest opened 320~% red light. Thf main using rubicund and phase displacer x3 every fight. Something is not right with HMP drop when using this addon, considering the drop rate is around 6% and I can get them just fine when manual farming using Rubicund+Cobalt.

Also is there any way to use Cobalt cell in this addon? I didn't see any mention of it in the code when skimming over it.

Edit: Did another 500 and got 3 pouches to drop. So this was a false alarm. The addon does indeed work correctly. However, the drop rate is still excessively low compared to what's reported(XIVDB reports 6%, where I am essentially getting a .6% drop rate using only rubi cells). If it's not too much trouble, would you mind adding cobalt cell support to this lua? From what I read online it helps with HMP drops when the VW campaign is not active. I have no idea where to even begin on trying to add this on myself.

**Comment by Icydeath** [comment]
I'll take a look at adding colbalt cell to it, might be a hot minute before i get it updated though.

**Comment by Icydeath** [comment]
@berkleyson I've added the support for cobalt cells, made some code adjustments and updated the help command.
Let me know if it works because I haven't had the chance to test it myself. If it doesn't work please open a new issue.
