### ISSUE TITLE
finalAlert missing files and I would like to contact the original author

### ISSUE THREAD

**Issue by thecuriousorange** [Icydeath/ffxi-addons#14]
the images folder, and subfolders that the addon depends upon are missing from this repository.
due to this, another person and I have made adjustments to the addon, I would like to post this addon to the official repo with the permission of the original author. do you have any means to contact them or pass on a request for permission?

**Comment by Icydeath** [comment]
I don't even remember this addon or where I found it. Which is probably why I removed it from the repo.
I know I found some addons on pastebin and ffxiah forums if you wanted to try and search those places. I'll check my backup files though and if I find it with the images folder I'll reply to this.

**Comment by thecuriousorange** [comment]
found a complete version of finalAlert, sent a pull request I think

**Comment by Icydeath** [comment]
Accepted pull request. Nice work @thecuriousorange
