### ISSUE TITLE
gambits - Engaged trigger

### ISSUE THREAD

**Issue by stickynoteme** [Icydeath/ffxi-addons#17]
There's a "NOT_ENGAGED" trigger but I would like an "Engaged" trigger. 

I'm trying to automate Haste Samba, and as is using:

{"SELF","NOT_STATUS","Haste Samba","JA","Haste Samba"}

Will just keep Haste samba up 100% of the time and eat through all my TP even when I'm not in battle.

Also on Sam it's really nice having Hasso automated but same issue since it keeps it up outside of battle I have to disable the whole script every time I want to walk anywhere.

**Comment by stickynoteme** [comment]
Figured out how to add it myself, thanks for the clean code, I'm amazed I was able to do it since I hadn't ever done anything with Lua before.

**Comment by Icydeath** [comment]
just want to state that the code isn't mine at all. Its just something I found and was sharing with others. Glad you were able to figure it out.
