### ISSUE TITLE
Singer

### ISSUE THREAD

**Issue by Mcdougall1** [Icydeath/ffxi-addons#18]
Is there any way to make it sing 5 songs with clarion? I can set it to minuet X3 and March X2 but it'll just spam songs over and over.  If i set it to 2 march 2 minuet it'll let the 5th song fall off. Clarion:[Minuet] is on. Not sure what i could be missing if its allready possible. Thank you!

**Comment by Icydeath** [comment]
Hmm, I think I see the issue but I'm not currently subbed at the moment.
It looks like Ivaar (original creator) has a newer version then the one I modified: 
https://github.com/Ivaar/Windower-addons/tree/master/Singer

Give Ivaar's Singer a try, just make a backup of your current singer folder (rename it to something like 'Singer_backup') and start fresh with his version.
If you can't get his version to work please let me know and I'll turn you into my guinea pig... I mean test user :)

**Comment by Mcdougall1** [comment]
Haha okay I’ll give it a shot but keep in mind there’s a return home
campaign until January 5 :) lol

I’ll be happy to be your Guinea pig though haha

**Comment by Mcdougall1** [comment]
So i tried out ivaars updated and it seems to be working only problem i'm having with his its not automatically switching to dummy extra songs (gs c extrasongsmode) but if you dont have time i'll just make a work around for it

Thank you icydeath :) I love your work

**Comment by Icydeath** [comment]
Figured that was the reason why you were using my version :). I can probably add that part in to his latest version. I'll reply back to this thread when I have something up in the repo.

**Comment by Mcdougall1** [comment]
That would be amazing lol, thank you

**Comment by Icydeath** [comment]
[Singer_update.zip](https://github.com/Icydeath/ffxi-addons/files/7795170/Singer_update.zip)
Can you give this a try?
- Unload singer
- Rename your settings.lua file to settings-backup.lua
- Replace the singer files with these files
- Load singer to generate a new settings.lua file.
- In the settings.lua you will now see the gearswap setting, change it if needed and reload singer.

**Comment by Mcdougall1** [comment]
I let it run for a while its still maintaining Clarions 5 buffs and
pianoism on another char and swapping the buffs with my gearswap :D Your
awesome that was fast, thank you.

**Comment by Mcdougall1** [comment]
I did notice something it does use dummy songs even when 5 songs are allready up. Is there any way to fix this?

**Comment by Mcdougall1** [comment]
I deleted the other responses. So i noticed it ended up dropping Clarion's call buff i'm gonna play around with it and try to figure out why. but the gs c is swapping to dummies which is the most important part just not sure why it stopped watching clarion.  It also randomly through a dummy set in before it let it drop as if it had 0 songs up. But i did change one of my characters jobs not the bard but the rdm to a whm because i wanted to change my pianoism song order up. So i'm gonna reset my two hour and let it try again without changing jobs.

**Comment by Mcdougall1** [comment]
Yeah i'm not sure what i did the first time around it appears to be working now. Thank you again icydeath! i appreciate you.

**Comment by Icydeath** [comment]
Glad I could help! I'll have to get that version up in my repo... in the morning :) zzz
