### ISSUE TITLE
Maneuvers need to be spelt fully

### ISSUE THREAD

**Issue by Mcdougall1** [Icydeath/ffxi-addons#19]
Hey Icy i'm not sure if your around but i have a question. Would you be able to add manever shortcuts? so insead of typing out fire manuver  i cant just type out fire as the //pup help shows. Thank you :D

**Comment by Icydeath** [comment]
interesting, i've just always used the auto-trans and never noticed the issue with that. Thanks for pointing it out and I'll work on it asap.

As a work around you should be able to do "_//pup man 1 fire m_" by adding the " m" it'll correctly grab the maneuver... in theory :)

**Comment by Icydeath** [comment]
Actually just committed a fix.
Here is just the lua file so you don't have to DL the whole repo if you haven't cloned it via git
[AutoPUP.zip](https://github.com/Icydeath/ffxi-addons/files/7876403/AutoPUP.zip)
.

**Comment by Mcdougall1** [comment]
Thank you!
