### ISSUE TITLE
WKR

### ISSUE THREAD

**Issue by Lilfrosty** [Icydeath/ffxi-addons#2]
Hey Icy, wasn't sure how else to get a hold of you. Wondering if this WKR/HTMB automates the said events...similar to the Quetz addon. Any help would be appreciated!

**Comment by Icydeath** [comment]
Sorry for the delay (bah work).
No they do not, they automate the entering the battle fields using packets. Very useful when running multiple toons.

**Comment by Lilfrosty** [comment]
Okay I see, thank you for the answer :)
