### ISSUE TITLE
Do you know the sell function in AuctionHelper?

### ISSUE THREAD

**Issue by comola** [Icydeath/ffxi-addons#20]
Hi Icydeath,

Sorry to border you but do you know the code behind the AuctionHelper? I been trying to sell item to auction house with the addon. It seem broken. However bidding is ok. I try to read the code but got confuse.

Can you please help me?

Thank you
Comola

**Comment by Icydeath** [comment]
sell [item name] [stack] [price] -- sell an item, must open ah once after addon has loaded/players logged in.

//ah sell Alexandrite stack 350000
//ah sell Alexandrite single 2000

**Comment by Icydeath** [comment]
If you are having issues with the one in my Repo, try updating auctionhelper from the original creator Ivaar: https://github.com/Ivaar/Windower-addons/tree/master/AuctionHelper
