### ISSUE TITLE
Multibox poke_box

### ISSUE THREAD

**Issue by ZariannaPlays** [Icydeath/ffxi-addons#24]
Issue with poking box while multiboxing, I assume it's from interacting with the box at the same with with multiple characters. Is there a way to add a retry/wait time for party member 0-5?

**Comment by Icydeath** [comment]
Which addon are you referring to exactly?

**Comment by Icydeath** [comment]
I'm guessing you are asking about Voidwatch.lua based on the other issues you've created. Going to state it again here for reference

"The one I have here is a version behind. Please see dabidobido's github page for the latest version."
https://github.com/dabidobido/FFXIAddons

If its not about voidwatch feel free to open up a new issue with the addons name in the title.
