### ISSUE TITLE
Generating Error when weapons are not in Inventory

### ISSUE THREAD

**Issue by wjctampa** [Icydeath/ffxi-addons#25]
Hi Icy,

Ran across this issue today, not sure what's changed.  Upon loading Autoskillchain and Cycling to select preferred skillchain, I've been getting the error below
![image](https://user-images.githubusercontent.com/6455221/160288949-3cc168e0-b22d-4f00-a576-b8446f6e7454.png)

I have setup specific sets depending on currently equipped weapons.  I've also moved the weapons from Wardrobe into Inventory and that corrects the issue. 

Upon reviewing the lua, it's referencing the main_bag, at least from what I see with my limited coding experience.  How do we add support to include Wardrobes?

**Comment by Icydeath** [comment]
off the top of my head, main_bag references inventory+wardrobes, but I believe the last update might have mucked it up with the additional wardrobes. I'll take a look shortly

**Comment by Icydeath** [comment]
change the bags variable at the top to:
`local bags = {[0]='inventory',[8]='wardrobe',[10]='wardrobe2',[11]='wardrobe3',[12]='wardrobe4',[13]='wardrobe5',[14]='wardrobe6',[15]='wardrobe7',[16]='wardrobe8'}`

Hopefully that's all there is to it. Let me know how it goes

**Comment by wjctampa** [comment]
Thank you much.   That fixed it.
