### ISSUE TITLE
autochain error

### ISSUE THREAD

**Issue by qe58hmr** [Icydeath/ffxi-addons#27]
hi icy,

autochain works great when its work but i keep getting now and then this massge 
autochain: lua runtime error: autochain/autochain/lua:247: attempt to index field '?' (a nil value)

**Comment by Icydeath** [comment]
Honestly I had no idea if anyone was using this haha. It's only been lightly tested as well so thank you for giving it a shot.

So its having an issue determining the level of the skillchain, when this error occurs do you know what level of skillchain that's being created? Also if the skillchain gets interrupted midway through I think something like this could also happen... Regardless, I'll add some logic around this to help prevent the error from occurring.

**Comment by qe58hmr** [comment]
99% of the time step 2

**Comment by Icydeath** [comment]
Can you give this version a try when you get a chance, please?

[AutoChain.zip](https://github.com/Icydeath/ffxi-addons/files/8541335/AutoChain.zip)

**Comment by qe58hmr** [comment]
thanks bro will do

**Comment by qe58hmr** [comment]
played a bit with apex its working really great but i got same error when victory smite -> lvl 4 light

**Comment by qe58hmr** [comment]
step 2 savage blade
victory smite -> lvl 4 light

**Comment by qe58hmr** [comment]
till step 2 works good when step 3 its gives same error

**Comment by Icydeath** [comment]
very interesting - I'm going to have to dig into that further. Thanks for testing it and I'll share the next version when I figure out what exactly is going on :)

**Comment by Icydeath** [comment]
Sorry @qe58hmr, I haven't had time to really dig into this and haven't been subbed to xi for months. I'm going to close this for now, but I have it on my list of todo's for when I do decide to come back :)
