### ISSUE TITLE
dupefiend potential error

### ISSUE THREAD

**Issue by sonime** [Icydeath/ffxi-addons#28]
Hello. I may be misunderstanding the plugin, but it doesn't seem to be doing much. a //df get put says it's getting and putting things, but it's not actually moving anything. Is the plugin meant to actually movie items, or list them? Furthermore, I can't actually seem to find the way to list what's in multiple places and where they are.

**Comment by Icydeath** [comment]
if i remember correctly dupefind is more of a reporting tool then a consolidation tool.

If you are interested in something that moves and consolidates materials and items then you should give storemats a try:
https://github.com/Icydeath/ffxi-addon-storemats
