### ISSUE TITLE
Currencies update

### ISSUE THREAD

**Issue by Heretic6667** [Icydeath/ffxi-addons#29]
Hi Icy- I know the update is still fresh, but wanted to throw out there that SE updated the currencies that are tracked in the Currencies 2 menu.  Hopefully its an easy update to the Currencies addon to have these new items displayed as well:

Domain Points / Domain Points earned today / Mog Segments / Gallimaufry

<3

**Comment by Icydeath** [comment]
Hi Heretic,
Just an FYI, this was an addon created by Ivaar. (https://gist.github.com/Ivaar/a95d9e565bd9a0e2036179c0c8cdee58)
I'm not currently subbed, but I can try and help you. Looking at the code its "just" searching through a specific packet for the string you enter. Have you tried some of the newly tracked currency to see if it still functions? If it doesn't, please let me know what error it is throwing.

**Comment by Heretic6667** [comment]
my mistake!  I think I got it from your github and didn't notice the different author.

Just the generic error that it can't find currencies matching those names :(

![image](https://user-images.githubusercontent.com/65053603/184562013-9ce638c1-b604-4034-9348-e7e41689b8de.png)

![image](https://user-images.githubusercontent.com/65053603/184562050-77cad0a0-49c9-4261-8bad-c11555b470a4.png)
