### ISSUE TITLE
AutoVW Targeting

### ISSUE THREAD

**Issue by wjctampa** [Icydeath/ffxi-addons#3]
AutoVW is targeting the closest mob in the zone instead of the Planar Rift.  Any chance of looking into this or how to add targetid of the Rift to the lua to see if that corrects it.

**Comment by Icydeath** [comment]
closing this. Check out [voidwalker](https://github.com/Icydeath/ffxi-addons/tree/master/voidwalker) by mojo, look it up on github to make sure you have the lastest version as mine might not be up-to-date.
