### ISSUE TITLE
MoveItems Enhancement?

### ISSUE THREAD

**Issue by lcreed** [Icydeath/ffxi-addons#31]
I stumbled across this lua in your repo and its tagged as written by Ivaar.  I'm not finding it in his repos or I'd hit him up with this question.  I love this in my mog garden for putting items in the right places but its not letting me put things in the safes or storage.  I don't see where bags are defined.  Is it possible to expand this to store items in all bags if you're in MH or garden where you have access to all?

**Comment by Icydeath** [comment]
I looked for it as well and couldn't find it. :(
I personally use the addon "itemizer" by Ihina, which is also in my repo. You should check it out.
