### ISSUE TITLE
Question about an Addon if you have time

### ISSUE THREAD

**Issue by Mercurian** [Icydeath/ffxi-addons#4]
Been looking for a long time for a lua to open Emblazoned Reliquary chests in escha, I know one exists I just can't find it.

Do you know about it/one or do you think you could make one?

**Comment by Icydeath** [comment]
Sadly, I do not know of any lua's that loot the escha chests. I actually never really looked around for it before. Let me do some digging first and ask around. If I come up empty and I have the time I'll make something quick and dirty ;)

**Comment by Mercurian** [comment]
Fantastic. Would be incredibly appreciated. I know that something exists because I see other people using it... they just won't say what it is or where they got it.

**Comment by Mercurian** [comment]
Any word on this?

**Comment by Icydeath** [comment]
I just haven't had the time yet to dig into it.

**Comment by Mercurian** [comment]
Understandable

**Comment by Mercurian** [comment]
Few weeks bump, just a reminder that I still care about having it done, if you still haven't found time.

**Comment by Icydeath** [comment]
Some time is freeing up - So i'm on the case! I'm going to dig around github / discord to see if anyone has something already. If not, I'll attempt to create something. May take some time due to real life + I've never played around with scripts opening boxes in escha before... I'll try and keep you posted the best I can.

**Comment by Mercurian** [comment]
I know that there is one, I just don't know where it is, what it's called or if it's for ashita only. I know people who use it, they're just to greedy to give any info on it.  This guy for example https://www.ffxiah.com/player/Asura/Colbrit

**Comment by Icydeath** [comment]
I understand your frustration! Which is one of the reasons why I try to
mass as much as I can on my github! I don't think most of them do it on
purpose, I think its more of "oh I thought everyone had this already"....
but then I'm sure there are a few that are just keeping stuff to themselves
to keep their own pockets lined with that fat gilz. Which, I can't blame
them for that.. if they spent the time creating it, they have that right
not to share it.

Anyways, we'll figure something out :-D! The community as a whole are good
people, so I'm sure if I reach out to the right people we'll get some
assistance or at the very least, pointed in the right direction.

Just wondering. Did you ever reach out in Discord? I don't want to keep
bugging them about the same thing if you have already reached out to them
^.^;

**Comment by Mercurian** [comment]
Nah, I haven't talked to anyone on discord or windower forums etc, only on ah but no answers

**Comment by Icydeath** [comment]
@Mercurian I've made good progress - may need some help testing if interested. Send me an email at icemanbg8(at)gmail.com and I'll send you what I have + instructions for testing when I get to that point.

I'm going to be busy Saturday, but Sunday I should get a little more time to work on it.

**Comment by Mercurian** [comment]
Dropped you an email

**Comment by maudit867** [comment]
Was a solution ever found for this?

**Comment by Icydeath** [comment]
Negative, but I will being looking into it again at some point.

**Comment by Icydeath** [comment]
@maudit867 i've added a addon call [EschaChest](https://github.com/Icydeath/ffxi-addons/tree/master/EschaChest). it needs to be improved but it does work.
