### ISSUE TITLE
Question about Assistme

### ISSUE THREAD

**Issue by bjggi** [Icydeath/ffxi-addons#5]
Hi, i have a question :)

How does Assistme work? Does it auto. engage on Mule, if my Main engages?

I tried to enter my Main's Name in the Lua and load it on my mule. 

I tried some options but not really working. 

Best regards

**Comment by Icydeath** [comment]
That's a good question, i've actually never tried the addon myself :D

**Comment by Icydeath** [comment]
Just a quick thought. Do you have shortcuts addon loaded? Most addons utilize it and assume all users have it running. Just checking! :-D
I'll play around with it when I get a minute!

**Comment by bjggi** [comment]
:) Yah Shortcuts was loaded.  And no Problem.

**Comment by Icydeath** [comment]
bjggi - you may want to take a look at '[AttackWithMe](https://github.com/yyoshisaur/attack-related_addon)' works well, doesn't run to the mob and face it but I may take some time modify it to do so ^.^; If I do, I'll add it to my repository. (sorry for the super late reply, just wanted to follow up with you with what I found).
