### ISSUE TITLE
packet loss?

### ISSUE THREAD

**Issue by WhySoSerious399** [Icydeath/ffxi-addons#6]
Tested Multiple times, even have other with the same problem. 
Alt that Mimics is not equipping BP delay gear.Tested by changing main and alt. Confirmed issue IMO

**Comment by Icydeath** [comment]
To which addon are you referring to?

**Comment by WhySoSerious399** [comment]
oops sorry. SendTarget

**Comment by Icydeath** [comment]
Maybe out of date on my github:
Please try the original developers version:
https://github.com/DiscipleOfEris/SendTarget

If you are still having issues you may want to open a ticket on their github.

**Comment by WhySoSerious399** [comment]
ok
