### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Nitroboy2010** [Icydeath/ffxi-addons#8]
Hello,
is Naga.lua broken or am i missing something? 
i did set the home point in misareaux and did set the trusts. then loaded the lua, but then it says: Waiting at X: -10.93875276 Y: -203.37429877 .
when i zone out and back into misareaux, it tells me not to forget to set a home point.
That's all it does.

**Comment by Icydeath** [comment]
I'll take a look

**Comment by Icydeath** [comment]
@Nitroboy2010
"when i zone out and back into misareaux..."
Do you mean after the dragon dies it warps you out and then just sits there?

**Comment by Nitroboy2010** [comment]
No, it does nothing at all. it does not move an inch. i used the HP to zone out then zone in again.

**Comment by Icydeath** [comment]
Nothing jumps out at me of why it wouldn't be doing anything at all.. Tomorrow I'll jump online and test it to see if I get the same results.

Do you have shortcuts addon running? I think it may require that addon to function correctly... I'll know for sure when I test drive it tomorrow.
