### ISSUE TITLE
A question about HealBot

### ISSUE THREAD

**Issue by selu32** [Icydeath/ffxi-addons#9]
Hi Icy,

First I just wanted to say I've been using your addon repository a ton and it's been invaluable. Thanks for maintaining this great list!

I've been trying to use the HealBot addon on my COR, and I wanted to have it assist my main, engage the mob, run into melee range and spam Savage Blade. This works well enough except for one thing: when engaged, the COR will constantly run through the mob and back until I force it to stop attacking. Is this a problem you've encountered before? If so, are you aware of a solution?

Let me know if there's any other info you need.

**Comment by Icydeath** [comment]
Hi Selu32,
I'm glad you like repo and I wish I had more time to keep it up-to-date!

I'm guessing its due to the follow distance? try //hb follow distance 3
see if that helps.

If it doesn't then I would recommend using AutoWS + AttackWithMe addons
AttackWithMe can be found here: https://github.com/yyoshisaur/attack-related_addon/tree/master/attackwithme

Hope this helps,
Icy

**Comment by selu32** [comment]
Thank you for your response! And sorry about my late reply.

I tried both pieces of advice, and ran into problems with both unfortunately.

For healbot, your suggestion to change the follow distance worked in conjunction with setting a character as a follow target (previous i hadn't set anyone to follow), but now the COR will engage and face the follow target rather than the monster.

For attackwithme, engaging works fine, but the COR won't run in to melee range, and I don't think (I'll have to test again) they're facing the monster either. The running into melee range I have ideas about how to fix, however.

Just wanted to report back with my findings. If you have any other advice I would definitely appreciate it, just shoot me an e-mail. Otherwise thanks again!

**Comment by Icydeath** [comment]
@selu32  I've modded attackwithme and added it to my repo. Give it a try.
[https://github.com/Icydeath/ffxi-addons/tree/master/attackwithme](https://github.com/Icydeath/ffxi-addons/tree/master/attackwithme)
